#!/bin/bash

echo 'You should be using a proper dependecy scanner such as OWASP Dependency Check! Go check it out at: https://owasp.org/www-project-dependency-check/'

echo 'You can run as a binary: dependency-check.sh --project \"<project-name>\" --scan \"<directory-to-scan>\'
echo 'Or for Maven projects: mvn org.owasp:dependency-check-maven:aggregate'
